name: reliz_protocol
description: Reliz Protocol - Stealth VPN Client
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  app_links: ^6.3.0 # Добавили пакет для Диплинков, под который Девин писал код

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^11.0.0

flutter:
  uses-material-design: true