// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProxyStatus`

/// Запустить Reliz-прокси с заданными параметрами.
///
/// Вызывается из Flutter при нажатии кнопки "Connect".
///
/// # Параметры
/// * `server_addr` — адрес Reliz-сервера, например `vpn.example.com:443`.
/// * `user_id` — UUID пользователя (32 hex-символа, без дефисов).
/// * `enable_padding` — добавлять Dynamic Padding в исходящие фреймы.
/// * `enable_fragmentation` — фрагментировать TLS ClientHello (anti-DPI).
/// * `mask_domain` — домен SNI/Reality, под который маскируется клиент
///   (например, `www.apple.com`). Передаётся в `ClientConfig` и далее
///   в TLS-обёртку клиента — раньше Flutter-приложение его игнорировало.
Future<int> startRelizProxy(
        {required String serverAddr,
        required String userId,
        required bool enablePadding,
        required bool enableFragmentation,
        required String maskDomain}) =>
    RustLib.instance.api.crateApiStartRelizProxy(
        serverAddr: serverAddr,
        userId: userId,
        enablePadding: enablePadding,
        enableFragmentation: enableFragmentation,
        maskDomain: maskDomain);

/// Остановить прокси.
Future<int> stopProxy() => RustLib.instance.api.crateApiStopProxy();

/// Получить текущий статус прокси.
Future<int> getProxyStatus() => RustLib.instance.api.crateApiGetProxyStatus();

/// Проверить, запущен ли прокси.
Future<bool> isProxyRunning() => RustLib.instance.api.crateApiIsProxyRunning();

/// Протестировать подключение к серверу.
Future<int> testConnection({required String serverAddr}) =>
    RustLib.instance.api.crateApiTestConnection(serverAddr: serverAddr);

/// Получить версию протокола.
Future<int> getProtocolVersion() =>
    RustLib.instance.api.crateApiGetProtocolVersion();
